apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
  selector:
    app: {{ include "postgres.fullname" . }}
