# Dev overrides for product-service
# Usage: helm install product-service ./charts/product-service -n quickkart-dev -f environments/dev/product-service.yml

replicaCount: 1

image:
  repository: rickdevma100/quickkart-product-service
  pullPolicy: IfNotPresent
  tag: "1.0.1"

database:
  host: product-db-postgres
  port: 5432
  name: productdb
  username: postgres
  password: password

service:
  type: ClusterIP
  port: 8082

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80


